In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
dataset="ecg.csv"
df = pd.read_csv(dataset)

n= df.shape[0]
class_1= len(df[df['Label']==1])
class_0= len(df[df['Label']==0])

print(n)
print(class_0)
print(class_1)


4998
2079
2919


In [3]:
y = df['Label']
X = df.drop('Label', axis=1)


scaler = MinMaxScaler()
scaled_df=scaler.fit_transform(df)

X_train, X_test, y_train, y_test = train_test_split(scaled_df, y, test_size=0.3, random_state=42)



In [4]:
#One Class SVM

from sklearn import svm

model = svm.OneClassSVM(kernel='linear', gamma=0.1)
normal_data = X_train[y_train == 1]
model.fit(normal_data)

y_pred = model.predict(X_test)

y_pred[y_pred == 1] = 1 
y_pred[y_pred == -1] = 0  

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# print(y_test)
# print(y_pred)

Accuracy: 0.7153333333333334
Confusion Matrix:
[[622   0]
 [427 451]]


In [176]:
# KNN

from sklearn.neighbors import NearestNeighbors

k=5
threshold=0.6

knn_model=NearestNeighbors(n_neighbors=k)
knn_model.fit(X_train,y_train)

distances, _ = knn_model.kneighbors(X_test)

kth_distances = distances[:, -1]

y_pred=[]

for distance in kth_distances:
    if distance > threshold:
        y_pred.append(0)
    else:
        y_pred.append(1)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.5766666666666667
Confusion Matrix:
[[ 56 566]
 [ 69 809]]


In [5]:
#Isolation Forests

from sklearn.ensemble import IsolationForest

c=float(class_0) / n
isolation_forest_model = IsolationForest(contamination= c , random_state=42)

isolation_forest_model.fit(X_train)

y_pred = isolation_forest_model.predict(X_test)

# Convert predictions to binary labels: 1 for inliers (normal), 0 for outliers (anomalies)
y_pred_binary = [1 if x == 1 else 0 for x in y_pred]

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_binary)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.624
Confusion Matrix:
[[343 279]
 [285 593]]
