In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Variant_III.csv")
df.head(5)

fraud_bool  income  name_email_similarity  prev_address_months_count  \
0           0     0.5               0.489311                         24   
1           0     0.9               0.535394                         -1   
2           0     0.5               0.188964                         -1   
3           0     0.4               0.391397                         29   
4           0     0.1               0.592711                         -1   

   current_address_months_count  customer_age  days_since_request  \
0                            20            50            0.019819   
1                            82            40            0.007959   
2                            73            60            0.027117   
3                             5            20            0.021103   
4                           267            40            0.039380   

   intended_balcon_amount payment_type  zip_count_4w  ...  foreign_request  \
0               -0.857899           AC          1842  ...                0   
1               -1.560356           AB          1241  ...                0   
2               -0.897317           AC          1095  ...                0   
3               -0.473215           AB           888  ...                0   
4               16.213862           AA           599  ...                0   

     source  session_length_in_minutes  device_os  keep_alive_session  \
0  INTERNET                   1.873109      other                   0   
1  INTERNET                  20.170591      linux                   1   
2  INTERNET                   1.722109      other                   1   
3  INTERNET                   2.152433      linux                   1   
4  INTERNET                  14.204698      other                   0   

  device_distinct_emails_8w  device_fraud_count  month        x1        x2  
0                         1                   0      0 -0.351078 -0.429230  
1                         1                   0      0 -0.424817  0.394155  
2                         1                   0      0 -1.974833  0.332406  
3                         1                   0      0 -0.579442  0.427254  
4                         1                   0      0  1.915776  1.363967  

[5 rows x 34 columns]

In [4]:
fraud=len(df[df['fraud_bool']==0])
no_fraud=len(df)-fraud

print(no_fraud)
print(fraud)

11030
988970


In [5]:
df.drop('prev_address_months_count', axis=1, inplace=True)
df.drop('intended_balcon_amount', axis=1, inplace=True)
df.drop('device_os', axis=1, inplace=True)
df.drop('zip_count_4w', axis=1, inplace=True)
df.drop('velocity_4w', axis=1, inplace=True)
df.drop('velocity_24h', axis=1, inplace=True)
df.drop('velocity_6h', axis=1, inplace=True)
df.drop('bank_branch_count_8w', axis=1, inplace=True)
df.drop('date_of_birth_distinct_emails_4w', axis=1, inplace=True)

In [6]:
low_income=0.2
high_income=0.7

def category_income(income):
    if income <= low_income:
        return 1
    elif low_income < income <= high_income:
        return 2
    else:
        return 3

df['income']=df['income'].apply(category_income)
df['income']=df['income'].astype('int64')

df.head(10)
    

fraud_bool  income  name_email_similarity  current_address_months_count  \
0           0       2               0.489311                            20   
1           0       3               0.535394                            82   
2           0       2               0.188964                            73   
3           0       2               0.391397                             5   
4           0       1               0.592711                           267   
5           0       2               0.808857                            33   
6           0       1               0.578367                           214   
7           1       2               0.008152                           150   
8           0       2               0.323435                             3   
9           0       3               0.999471                             7   

   customer_age  days_since_request payment_type employment_status  \
0            50            0.019819           AC                CC   
1            40            0.007959           AB                CA   
2            60            0.027117           AC                CA   
3            20            0.021103           AB                CA   
4            40            0.039380           AA                CA   
5            50            0.013682           AA                CB   
6            60            0.001029           AD                CA   
7            60            3.187310           AA                CC   
8            30            0.015521           AB                CA   
9            50            0.009806           AB                CA   

   credit_risk_score  email_is_free  ... proposed_credit_limit  \
0                151              0  ...                 500.0   
1                209              0  ...                1500.0   
2                106              1  ...                 200.0   
3                243              1  ...                1500.0   
4                157              1  ...                1500.0   
5                 73              0  ...                 200.0   
6                116              0  ...                 200.0   
7                 45              1  ...                 500.0   
8                106              0  ...                1000.0   
9                206              0  ...                1500.0   

   foreign_request    source  session_length_in_minutes  keep_alive_session  \
0                0  INTERNET                   1.873109                   0   
1                0  INTERNET                  20.170591                   1   
2                0  INTERNET                   1.722109                   1   
3                0  INTERNET                   2.152433                   1   
4                0  INTERNET                  14.204698                   0   
5                0   TELEAPP                   3.569949                   0   
6                0  INTERNET                   4.493626                   1   
7                0  INTERNET                  13.906284                   1   
8                0  INTERNET                  11.521018                   1   
9                0  INTERNET                   5.704654                   1   

   device_distinct_emails_8w  device_fraud_count month        x1        x2  
0                          1                   0     0 -0.351078 -0.429230  
1                          1                   0     0 -0.424817  0.394155  
2                          1                   0     0 -1.974833  0.332406  
3                          1                   0     0 -0.579442  0.427254  
4                          1                   0     0  1.915776  1.363967  
5                          0                   0     0  1.156669 -0.653909  
6                          1                   0     0 -1.277008 -1.495283  
7                          1                   0     0  0.286904 -2.320594  
8                          1                   0     0 -0.560070 -0.142031  
9     

In [7]:
df['name_email_similarity']=df['name_email_similarity'].apply(lambda x: round(x,3))

low=0.3
high=0.6
def category_email(similarity):
    if similarity <low:
        return 1
    elif low < similarity <= high:
        return 2
    else:
        return 3

df['name_email_similarity']=df['name_email_similarity'].apply(category_email)
df['name_email_similarity']=df['name_email_similarity'].astype('int64')

df.head(10)


fraud_bool  income  name_email_similarity  current_address_months_count  \
0           0       2                      2                            20   
1           0       3                      2                            82   
2           0       2                      1                            73   
3           0       2                      2                             5   
4           0       1                      2                           267   
5           0       2                      3                            33   
6           0       1                      2                           214   
7           1       2                      1                           150   
8           0       2                      2                             3   
9           0       3                      3                             7   

   customer_age  days_since_request payment_type employment_status  \
0            50            0.019819           AC                CC   
1            40            0.007959           AB                CA   
2            60            0.027117           AC                CA   
3            20            0.021103           AB                CA   
4            40            0.039380           AA                CA   
5            50            0.013682           AA                CB   
6            60            0.001029           AD                CA   
7            60            3.187310           AA                CC   
8            30            0.015521           AB                CA   
9            50            0.009806           AB                CA   

   credit_risk_score  email_is_free  ... proposed_credit_limit  \
0                151              0  ...                 500.0   
1                209              0  ...                1500.0   
2                106              1  ...                 200.0   
3                243              1  ...                1500.0   
4                157              1  ...                1500.0   
5                 73              0  ...                 200.0   
6                116              0  ...                 200.0   
7                 45              1  ...                 500.0   
8                106              0  ...                1000.0   
9                206              0  ...                1500.0   

   foreign_request    source  session_length_in_minutes  keep_alive_session  \
0                0  INTERNET                   1.873109                   0   
1                0  INTERNET                  20.170591                   1   
2                0  INTERNET                   1.722109                   1   
3                0  INTERNET                   2.152433                   1   
4                0  INTERNET                  14.204698                   0   
5                0   TELEAPP                   3.569949                   0   
6                0  INTERNET                   4.493626                   1   
7                0  INTERNET                  13.906284                   1   
8                0  INTERNET                  11.521018                   1   
9                0  INTERNET                   5.704654                   1   

   device_distinct_emails_8w  device_fraud_count month        x1        x2  
0                          1                   0     0 -0.351078 -0.429230  
1                          1                   0     0 -0.424817  0.394155  
2                          1                   0     0 -1.974833  0.332406  
3                          1                   0     0 -0.579442  0.427254  
4                          1                   0     0  1.915776  1.363967  
5                          0                   0     0  1.156669 -0.653909  
6                          1                   0     0 -1.277008 -1.495283  
7                          1                   0     0  0.286904 -2.320594  
8                          1                   0     0 -0.560070 -0.142031  
9     

In [8]:
num_bins = 5  
column_to_partition = 'credit_risk_score'
min_credit_score = df[column_to_partition].min()-1

bin_width = (df[column_to_partition].max() - min_credit_score) / num_bins

bin_edges = [min_credit_score + i * bin_width for i in range(num_bins + 1)]

bin_labels = [i for i in range(1, num_bins + 1)]

df['credit_risk_score'] = pd.cut(df[column_to_partition], bins=bin_edges, labels=bin_labels)
df['credit_risk_score'] = df['credit_risk_score'].astype('int64')
print(df['credit_risk_score'])

0         3
1         4
2         3
3         4
4         3
         ..
999995    4
999996    3
999997    3
999998    3
999999    4
Name: credit_risk_score, Length: 1000000, dtype: int64


In [9]:


df = pd.get_dummies(df, columns=['payment_type'], prefix='pt', drop_first=False)
os_columns = [col for col in df.columns if col.startswith('pt_')]

df = pd.get_dummies(df, columns=['employment_status'], prefix='emp', drop_first=False)
os_columns = [col for col in df.columns if col.startswith('emp_')]

df = pd.get_dummies(df, columns=['housing_status'], prefix='hs', drop_first=False)
os_columns = [col for col in df.columns if col.startswith('hs_')]

df = pd.get_dummies(df, columns=['source'], prefix='src', drop_first=False)
os_columns = [col for col in df.columns if col.startswith('src_')]

df.replace({False: 0, True: 1}, inplace=True)




/var/folders/dj/q9lcht6525s7fjd53lvkmcj40000gn/T/ipykernel_54191/3304083556.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({False: 0, True: 1}, inplace=True)


In [10]:
df.dropna(axis=0, inplace=True)

In [27]:
majority_class = df[df['fraud_bool'] == 0]
minority_class=df[df['fraud_bool']==1]

desired_majority_samples=70000
desired_minority_samples=500
undersampled_majority = majority_class.sample(n=desired_majority_samples, random_state=42)
undersampled_minority = minority_class.sample(n=desired_minority_samples, random_state=42)
undersampled_df = pd.concat([undersampled_majority,undersampled_minority])
undersampled_df = undersampled_df.sample(frac=1, random_state=42).reset_index(drop=True)
undersampled_y=undersampled_df['fraud_bool']
undersampled_x=undersampled_df.drop(columns=['fraud_bool'])

# X_train=undersampled_majority.drop(columns=['fraud_bool'])
# X_test= undersampled_df.drop(columns=['fraud_bool'])
# y_test=undersampled_df['fraud_bool']

from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(undersampled_x, undersampled_y, test_size=0.3, random_state=42)

model = svm.OneClassSVM(kernel='rbf', gamma=0.1)
model.fit(X_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)






Accuracy: 9.456264775413712e-05
Confusion Matrix:
[[    0     0     0]
 [19621     0  1386]
 [  141     0     2]]


In [26]:
from sklearn.neighbors import NearestNeighbors

k=3
threshold=0.5

knn_model=NearestNeighbors(n_neighbors=k)
knn_model.fit(X_train,y_train)

distances, _ = knn_model.kneighbors(X_test)

kth_distances = distances[:, -1]

y_pred=[]

for distance in kth_distances:
    if distance > threshold:
        y_pred.append(0)
    else:
        y_pred.append(1)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9898789878987899
Confusion Matrix:
[[4499    0]
 [  46    0]]


In [23]:
from sklearn.ensemble import IsolationForest

isolation_forest_model = IsolationForest(contamination= 0.01 , random_state=42)

isolation_forest_model.fit(X_train)

y_pred = isolation_forest_model.predict(X_test)

# Convert predictions to binary labels: 1 for inliers (normal), 0 for outliers (anomalies)
y_pred_binary = [1 if x == 1 else 0 for x in y_pred]

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_binary)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.019361936193619363
Confusion Matrix:
[[  44 4455]
 [   2   44]]
